server:
  port: 7900
spring:
  cloud:
    config:
      server:
        git:
          uri: Git仓库地址
          username: 账号名称
          password: 账号密码
          search-paths: config-repo
  application:
    name: dm-config-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@47.105.146.18:8761//eureka/,http://root:123456@47.105.146.18:8760//eureka/
  instance:
    prefer-ip-address: true