server:
  port: 7776
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://root:123456@192.168.1.9:7776/eureka/   #将自己注册到
#       defaultZone: http://root:123456@192.168.9.151:7776/eureka/
security:
  user:
    name: root
    password: 123456